# Generated by Django 2.2.10 on 2020-02-29 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='Hot search term')),
                ('index', models.IntegerField(default=0, verbose_name='sort')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Hot search ranking',
                'verbose_name_plural': 'Hot search ranking',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_sn', models.CharField(default='', max_length=50, verbose_name='product unique article number')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('click_num', models.IntegerField(default=0, verbose_name='clicks')),
                ('sold_num', models.IntegerField(default=0, verbose_name='Product Sales')),
                ('fav_num', models.IntegerField(default=0, verbose_name='number of favorites')),
                ('products_num', models.IntegerField(default=0, verbose_name='stock count')),
                ('market_price', models.FloatField(default=0, verbose_name='market price')),
                ('shop_price', models.FloatField(default=0, verbose_name='our shop price')),
                ('products_brief', models.TextField(max_length=500, verbose_name='item short description')),
                ('products_desc', models.TextField(max_length=500, verbose_name='product desc')),
                ('products_front_image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='cover image')),
                ('is_new', models.BooleanField(default=False, verbose_name='is new product')),
                ('is_hot', models.BooleanField(default=False, verbose_name='is it hot')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Product information',
                'verbose_name_plural': 'Product information',
            },
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Category Name', max_length=30, verbose_name='Cartgory Name')),
                ('code', models.CharField(default='', help_text='Category code', max_length=30, verbose_name='Cartgory code')),
                ('desc', models.TextField(default='', help_text='Description', verbose_name='Category Desc')),
                ('category_type', models.IntegerField(choices=[(1, 'First Class'), (2, 'Secodary'), (3, 'teritary')], help_text='Category Type', verbose_name='Category Type')),
                ('is_tab', models.BooleanField(default=False, help_text='is tab', verbose_name='is tab')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='parent Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='products.ProductsCategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Add Product',
                'verbose_name_plural': 'Add Product',
            },
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Products', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Commodity Carousel',
                'verbose_name_plural': 'Commodity Carousel',
            },
        ),
        migrations.CreateModel(
            name='ProductsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='品牌名')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.ProductsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': 'Add Category',
                'verbose_name_plural': 'Add Category',
                'db_table': 'products_productsbrand',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsCategory', verbose_name='Product Category'),
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.ProductsCategory', verbose_name='商品类目')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Products')),
            ],
            options={
                'verbose_name': 'Home ad',
                'verbose_name_plural': 'Home ad',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='carousel image')),
                ('index', models.IntegerField(default=0, verbose_name='carousel order')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Home Carousel',
                'verbose_name_plural': 'Home Carousel',
            },
        ),
    ]
