# Generated by Django 2.2.10 on 2020-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_desc',
            field=models.TextField(max_length=500, verbose_name='Product Description'),
        ),
    ]
