# Generated by Django 2.2.10 on 2020-03-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200301_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_sn',
            field=models.CharField(default='', max_length=50, verbose_name='product unique post number'),
        ),
    ]
