# Generated by Django 2.2.10 on 2020-03-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_content', models.TextField(help_text='original content', verbose_name='original content')),
                ('formatted_content', models.TextField(blank=True, help_text='processed content', null=True, verbose_name='processed content')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='modification time', null=True, verbose_name='modification time')),
            ],
            options={
                'verbose_name': 'Comment details',
                'verbose_name_plural': 'Comment detailslist',
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_level', models.IntegerField(default=0, help_text='comment level', verbose_name='comment level')),
                ('like_num', models.IntegerField(default=0, help_text='Number of Likes', verbose_name='Number of Likes')),
                ('unlike_num', models.IntegerField(default=0, help_text='counter number', verbose_name='counter number')),
                ('comment_num', models.IntegerField(default=0, help_text='Number of Comments', verbose_name='Number of Comments')),
                ('is_hot', models.BooleanField(default=False, help_text='is it hot', verbose_name='is it hot')),
                ('is_recommend', models.BooleanField(default=False, help_text='Recommended', verbose_name='Recommended')),
                ('is_active', models.BooleanField(default=True, help_text='is active', verbose_name='is active')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='Add Time', null=True, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Comment basic information',
                'verbose_name_plural': 'Comment basic informationlist',
            },
        ),
    ]
