# Generated by Django 2.2.10 on 2020-02-29 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('nonce_str', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='random encrypted string')),
                ('orders_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'Success'), ('TRADE_CLOSED', 'Timeout closed'), ('WAIT_BUYER_PAY', 'Transaction Creation'), ('TRADE_FINISHED', 'End of transaction'), ('paying', 'To be paid')], default='paying', max_length=30, verbose_name='Order Status')),
                ('pay_type', models.CharField(choices=[('alipay', 'Alipay'), ('wechat', 'Wechat')], default='alipay', max_length=10, verbose_name='payment type')),
                ('post_script', models.CharField(max_length=200, verbose_name='Order message')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='Order Amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='pay time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Shipping Address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='Signee')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='contact phone')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'order information',
                'verbose_name_plural': 'order information',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_num', models.IntegerField(default=0, verbose_name='number of products')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order item',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='purchased quantity')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
