# Generated by Django 2.2.10 on 2020-03-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlist',
            },
            bases=('material.postbaseinfo',),
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('CN', 'Chinese'), ('EN', 'English')], help_text='two language categories are now available', max_length=5, null=True, verbose_name='post details language category')),
                ('origin_content', models.TextField(blank=True, help_text='original content', verbose_name='original content')),
                ('formatted_content', models.TextField(help_text='processed content', verbose_name='processed content')),
                ('add_time', models.DateTimeField(blank=True, help_text='Add Time', null=True, verbose_name='Add Time')),
                ('update_time', models.DateTimeField(blank=True, help_text='modification time', null=True, verbose_name='modification time')),
                ('post_info', models.ForeignKey(blank=True, help_text='content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='post.PostInfo', verbose_name='content')),
            ],
            options={
                'verbose_name': 'Post Details',
                'verbose_name_plural': 'Post Detailslist',
            },
        ),
    ]
