# Generated by Django 2.2.10 on 2020-03-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('postbaseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.PostBaseInfo')),
            ],
            options={
                'verbose_name': 'Atlas',
                'verbose_name_plural': 'Atlaslist',
            },
            bases=('material.postbaseinfo',),
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='Add Time', null=True, verbose_name='Add Time')),
                ('album', models.ForeignKey(help_text='atlas', on_delete=django.db.models.deletion.CASCADE, to='album.AlbumInfo', verbose_name='atlas')),
                ('picture', models.ForeignKey(help_text='picture', on_delete=django.db.models.deletion.CASCADE, to='material.MaterialPicture', verbose_name='picture')),
            ],
            options={
                'verbose_name': 'Atlas Pictures',
                'verbose_name_plural': 'Atlas Pictureslist',
            },
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='pictures',
            field=models.ManyToManyField(help_text='picture', through='album.AlbumPhoto', to='material.MaterialPicture', verbose_name='picture'),
        ),
    ]
