# Generated by Django 2.2.10 on 2020-02-29 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='province')),
                ('city', models.CharField(default='', max_length=100, verbose_name='city')),
                ('district', models.CharField(default='', max_length=100, verbose_name='region')),
                ('address', models.CharField(default='', max_length=100, verbose_name='detailed address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='Signee')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='phone')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Shipping address',
                'verbose_name_plural': 'Shipping address',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
            ],
            options={
                'verbose_name': 'User Favorites',
                'verbose_name_plural': 'User Favorites',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'Message'), (2, 'Complaint'), (3, 'Ask'), (4, 'after sales'), (5, 'Buy')], default=1, help_text='Message type: 1 (message), 2 (complaint), 3 (inquiry), 4 (after-sale), 5 (purchase)', verbose_name='message type')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='topic')),
                ('message', models.TextField(default='', help_text='message content', verbose_name='message content')),
                ('file', models.FileField(help_text='uploaded file', upload_to='message/images/', verbose_name='uploaded file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Comments',
                'verbose_name_plural': 'User Comments',
            },
        ),
    ]
